# Generated by Django 5.1.5 on 2025-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('image', models.ImageField(upload_to='banners')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
