# Generated by Django 5.1.5 on 2025-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
