import { TProduct } from '@/types/product';

export const productsData: TProduct[] = [
  {
    id: 1,
    quantity: 22970,
    path: '/products/1',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 0,
    priceWithoutDiscount: 76530000,
    priceWithDiscount: 76530000,
    title: {
      fa: 'هدست پلی استیشن سونی اسلیم مدل پالس لایت وایرلس',
      en: 'Sony PlayStation 4 Headset Model PULSD',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-7.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/5-7.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 2,
    quantity: 15000,
    path: '/products/2',
    attributes: [
      { key: 'رنگ', value: 'نارنجی' },
      { key: 'برند', value: 'سونی' },
      { key: 'دسته بندی', value: 'گیمینگ' },
      { key: 'اقلام همراه', value: 'کابل و آداپتور' },
    ],
    discount: 15,
    priceWithoutDiscount: 55000000,
    priceWithDiscount: 47000000,
    title: {
      fa: 'کنسول بازی سونی مدل PlayStation 5',
      en: 'Sony PlayStation 5 Console',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-18.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/11.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-5.jpg',
    ],
    description: `کنسول بازی سونی با امکانات پیشرفته و طراحی زیبا. مناسب برای تجربه گیمینگ با کیفیت بالا.`,
  },
  {
    id: 3,
    quantity: 35000,
    path: '/products/3',
    attributes: [
      { key: 'رنگ', value: 'بنفش' },
      { key: 'برند', value: 'سامسونگ' },
      { key: 'دسته بندی', value: 'تبلت' },
      { key: 'اقلام همراه', value: 'شارژر و قلم' },
    ],
    discount: 0,
    priceWithoutDiscount: 12000000,
    priceWithDiscount: 12000000,
    title: {
      fa: 'تبلت سامسونگ مدل Galaxy Tab S7',
      en: 'Samsung Galaxy Tab S7',
    },
    category: {
      text: 'تبلت و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.jpg',
    ],
    description: `تبلت قدرتمند سامسونگ با صفحه نمایش 11 اینچی و عملکرد بی‌نظیر.`,
  },
  {
    id: 4,
    quantity: 19999,
    path: '/products/4',
    attributes: [
      { key: 'رنگ', value: 'قرمز' },
      { key: 'برند', value: 'شیائومی' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر و گارد' },
    ],
    discount: 5,
    priceWithoutDiscount: 32000000,
    priceWithDiscount: 30500000,
    title: {
      fa: 'موبایل شیائومی مدل Redmi Note 11',
      en: 'Xiaomi Redmi Note 11',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.jpg',
    ],
    description: `گوشی موبایل با دوربین قدرتمند و صفحه نمایش Full HD+.`,
  },
  {
    id: 5,
    quantity: 7800,
    path: '/products/5',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'لوازم جانبی' },
      { key: 'اقلام همراه', value: 'پاور بانک' },
    ],
    discount: 25,
    priceWithoutDiscount: 3000000,
    priceWithDiscount: 2250000,
    title: {
      fa: 'پاور بانک اپل مدل 5000 میلی‌آمپر',
      en: 'Apple Power Bank 5000mAh',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `پاور بانک سبک و با ظرفیت بالا برای شارژ دستگاه‌های مختلف.`,
  },
  {
    id: 6,
    quantity: 12000,
    path: '/products/6',
    attributes: [
      { key: 'رنگ', value: 'زرد' },
      { key: 'برند', value: 'هوآوی' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'گارد' },
    ],
    discount: 10,
    priceWithoutDiscount: 47000000,
    priceWithDiscount: 42000000,
    title: {
      fa: 'گوشی هوآوی مدل P40 Pro',
      en: 'Huawei P40 Pro',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گوشی پرچمدار هوآوی با دوربین فوق‌العاده و پردازنده سریع.`,
  },
  {
    id: 7,
    quantity: 25000,
    path: '/products/7',
    attributes: [
      { key: 'رنگ', value: 'آبی' },
      { key: 'برند', value: 'سونی' },
      { key: 'دسته بندی', value: 'هدفون' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 15,
    priceWithoutDiscount: 9800000,
    priceWithDiscount: 8300000,
    title: {
      fa: 'هدفون سونی مدل WH-1000XM4',
      en: 'Sony WH-1000XM4 Headphones',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.jpg',
    ],
    description: `هدفون‌های سونی با کیفیت صدا و نویزگیر عالی. مناسب برای گیمینگ و استفاده روزمره.`,
  },
      {
    id: 8,
    quantity: 42000,
    path: '/products/8',
    attributes: [
      { key: 'رنگ', value: 'بنفش' },
      { key: 'برند', value: 'سامسونگ' },
      { key: 'دسته بندی', value: 'گوشی موبایل' },
      { key: 'اقلام همراه', value: 'کابل شارژ' },
    ],
    discount: 12,
    priceWithoutDiscount: 9000000,
    priceWithDiscount: 7900000,
    title: {
      fa: 'گوشی سامسونگ مدل Galaxy A12',
      en: 'Samsung Galaxy A12',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گوشی سامسونگ با صفحه نمایش بزرگ و عملکرد مناسب.`,
  },
  {
    id: 9,
    quantity: 30000,
    path: '/products/9',
    attributes: [
      { key: 'رنگ', value: 'زرد' },
      { key: 'برند', value: 'آیفون' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 10,
    priceWithoutDiscount: 11000000,
    priceWithDiscount: 9900000,
    title: {
      fa: 'گوشی آیفون 12',
      en: 'iPhone 12',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `آیفون 12 با سیستم عامل iOS و دوربین دوگانه.`,
  },
  {
    id: 10,
    quantity: 18000,
    path: '/products/10',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'هوآوی' },
      { key: 'دسته بندی', value: 'لوازم جانبی' },
      { key: 'اقلام همراه', value: 'کابل شارژ' },
    ],
    discount: 10,
    priceWithoutDiscount: 3800000,
    priceWithDiscount: 3400000,
    title: {
      fa: 'کابل شارژ هوآوی مدل Fast Charging',
      en: 'Huawei Fast Charging Cable',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `کابل شارژ هوآوی برای شارژ سریع و کارکرد بالای دستگاه‌ها.`,
  },
  {
    id: 11,
    quantity: 15000,
    path: '/products/11',
    attributes: [
      { key: 'رنگ', value: 'زرد' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'گوشی موبایل' },
      { key: 'اقلام همراه', value: 'شارژر و گارد' },
    ],
    discount: 10,
    priceWithoutDiscount: 20000000,
    priceWithDiscount: 18000000,
    title: {
      fa: 'گوشی آیفون 11',
      en: 'iPhone 11',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گوشی آیفون 11 با دوربین دوگانه و عملکرد عالی.`,
  },
  {
    id: 12,
    quantity: 22000,
    path: '/products/12',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'شیائومی' },
      { key: 'دسته بندی', value: 'لوازم جانبی' },
      { key: 'اقلام همراه', value: 'گارد گوشی' },
    ],
    discount: 20,
    priceWithoutDiscount: 1500000,
    priceWithDiscount: 1200000,
    title: {
      fa: 'گارد گوشی شیائومی مدل ضد ضربه',
      en: 'Xiaomi Shockproof Phone Case',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گارد ضد ضربه شیائومی برای محافظت کامل از گوشی.`,
  },
  {
    id: 13,
    quantity: 30000,
    path: '/products/13',
    attributes: [
      { key: 'رنگ', value: 'بنفش' },
      { key: 'برند', value: 'هوآوی' },
      { key: 'دسته بندی', value: 'لوازم جانبی' },
      { key: 'اقلام همراه', value: 'هدفون' },
    ],
    discount: 15,
    priceWithoutDiscount: 6500000,
    priceWithDiscount: 5500000,
    title: {
      fa: 'هدفون هوآوی مدل FreeBuds 3i',
      en: 'Huawei FreeBuds 3i',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `هدفون بلوتوثی هوآوی با صدای استریو و میکروفن با کیفیت.`,
  },
  {
    id: 14,
    quantity: 30000,
    path: '/products/14',
    attributes: [
      { key: 'رنگ', value: 'زرد' },
      { key: 'برند', value: 'سونی' },
      { key: 'دسته بندی', value: 'گیمینگ' },
      { key: 'اقلام همراه', value: 'کیس و گیم پد' },
    ],
    discount: 10,
    priceWithoutDiscount: 7600000,
    priceWithDiscount: 6800000,
    title: {
      fa: 'گیم پد سونی مدل DualShock 4',
      en: 'Sony DualShock 4 Controller',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گیم پد سونی مدل DualShock 4 با طراحی ارگونومیک و دکمه‌های حساس.`,
  },
  {
    id: 15,
    quantity: 18000,
    path: '/products/15',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'لوازم جانبی' },
      { key: 'اقلام همراه', value: 'پاور بانک' },
    ],
    discount: 25,
    priceWithoutDiscount: 3800000,
    priceWithDiscount: 2850000,
    title: {
      fa: 'پاور بانک اپل مدل 10000 میلی‌آمپر',
      en: 'Apple Power Bank 10000mAh',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `پاور بانک اپل با ظرفیت بالا و طراحی زیبا برای شارژ سریع دستگاه‌ها.`,
  },
  {
    id: 16,
    quantity: 29000,
    path: '/products/16',
    attributes: [
      { key: 'رنگ', value: 'آبی' },
      { key: 'برند', value: 'هوآوی' },
      { key: 'دسته بندی', value: 'گوشی موبایل' },
      { key: 'اقلام همراه', value: 'کابل و گارد' },
    ],
    discount: 5,
    priceWithoutDiscount: 25000000,
    priceWithDiscount: 23750000,
    title: {
      fa: 'گوشی هوآوی مدل P30 Pro',
      en: 'Huawei P30 Pro',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گوشی هوآوی با دوربین عالی و باتری قدرتمند.`,
  },
  {
    id: 17,
    quantity: 25000,
    path: '/products/17',
    attributes: [
      { key: 'رنگ', value: 'قرمز' },
      { key: 'برند', value: 'شیائومی' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'گارد' },
    ],
    discount: 15,
    priceWithoutDiscount: 22000000,
    priceWithDiscount: 18700000,
    title: {
      fa: 'گوشی شیائومی مدل Mi 10T Pro',
      en: 'Xiaomi Mi 10T Pro',
    },
    category: {
      text: 'موبایل و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `گوشی شیائومی با پردازنده سریع و صفحه نمایش Full HD+.`,
  },
  {
    id: 18,
    quantity: 14000,
    path: '/products/18',
    attributes: [
      { key: 'رنگ', value: 'قرمز' },
      { key: 'برند', value: 'سامسونگ' },
      { key: 'دسته بندی', value: 'تبلت' },
      { key: 'اقلام همراه', value: 'کابل شارژ' },
    ],
    discount: 10,
    priceWithoutDiscount: 20000000,
    priceWithDiscount: 18000000,
    title: {
      fa: 'تبلت سامسونگ مدل Galaxy Tab S6',
      en: 'Samsung Galaxy Tab S6',
    },
    category: {
      text: 'تبلت و لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `تبلت سامسونگ با صفحه نمایش AMOLED و پردازنده عالی.`,
  },
  {
    id: 19,
    quantity: 28000,
    path: '/products/19',
    attributes: [
      { key: 'رنگ', value: 'زرد' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'لوازم جانبی' },
      { key: 'اقلام همراه', value: 'کابل شارژ' },
    ],
    discount: 20,
    priceWithoutDiscount: 5000000,
    priceWithDiscount: 4000000,
    title: {
      fa: 'کابل شارژ اپل مدل Lightning',
      en: 'Apple Lightning Cable',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `کابل شارژ اپل با سرعت بالا و کیفیت عالی.`,
  },
  {
    id: 20,
    quantity: 32000,
    path: '/products/20',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'هوآوی' },
      { key: 'دسته بندی', value: 'هدفون' },
      { key: 'اقلام همراه', value: 'کابل شارژ' },
    ],
    discount: 10,
    priceWithoutDiscount: 4500000,
    priceWithDiscount: 4050000,
    title: {
      fa: 'هدفون هوآوی مدل FreeBuds 4i',
      en: 'Huawei FreeBuds 4i',
    },
    category: {
      text: 'لوازم جانبی',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
    ],
    description: `هدفون بلوتوثی هوآوی با صدای استریو و حذف نویز فعال.`,
  },
];