# Generated by Django 5.1.5 on 2025-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
